<!doctype html>
<html ng-app="myApp">
    <head>
        <meta charset="utf-8" />
        <title>ZF2+Angular</title>
        <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="wrap">
            <div class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle Navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="#" class="navbar-brand">Base ZF2+AngularJs</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="#/categorias">Categorias</a></li>
                            <li><a href="#/produtos">Produtos</a></li>
                        </ul>
                    </div><!-- navbar-collapse -->
                </div>
            </div>
            <?=$this->content;?>
            <div id="footer">
                <div class="container">
                    <p class="text-muted credit">Ennio Simões</p>
                </div>
            </div>            
        </div><!-- Fim wrap -->
        <!--
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script>var $jQuery = jQuery.noConflict();</script>
        -->
        <script src="js/angular.min.js"></script>
        <script src="js/angular-route.min.js"></script>
        <script src="js/angular-resource.min.js"></script>
        <script src="projetoangular/app.js"></script>
        <script src="projetoangular/controllers.js"></script>
        <script src="projetoangular/services.js"></script>
    </body>
</html>